import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "./components/layouts/Sidebar";
import { ApolloWrapper } from "./lib/apollo-wrapper";

import { auth } from "../auth";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await auth();	

	return (
		<ApolloWrapper>
			<html lang="en">
				<body className="h-screen w-full overflow-hidden">
					<div className="flex h-full">
						{session?.user && (
							<div className="w-[10%] bg-slate-800 flex items-center px-2 py-10 gap-4 flex-col">
								<Sidebar />
							</div>
						)}

						<div className="w-[100%] bg-slate-200 h-full p-10">{children}</div>
					</div>
				</body>
			</html>
		</ApolloWrapper>
	);
}
